### ISSUE TITLE
Is the plugin ready for distribution ?

### ISSUE THREAD

**Issue by dregad** [turnermm/xcom#6]
Looking at the [README file](https://github.com/turnermm/xcom/blame/e3fddd9bc59cbca4d91daebbf35fe7f23b72746b/README.md#L7) which states `Currently in development. Not ready for distribution.`, but considering this note was written updated over 6 years ago and that there's been several releases since then, I was wondering about the actual status for this plugin...

Thanks !

Also, I noticed there's been several commits to master following the most recent official release (2019-06-14) e3fddd9bc59cbca4d91daebbf35fe7f23b72746b.

**Comment by turnermm** [comment]
Yes, it is readay.  Thanks for calling my attention to the inconsistencies in the information.  I just updated the date and removed the "Not ready for distribution" statement.


I've been working, on and off,  on a branch which does user-friendly options checking, to let you know beforehand if the options are not correct.  Currently the xmlrpc interface sends your request as written, and you have to wait for the response before you know whether you've made an error in entering your options.  And sometimes the response is not immediate.

**Comment by dregad** [comment]
Thanks for the feedback !
