### ISSUE TITLE
xcom plugin throws SyntaxError and ReferenceError, does not respond to user actions

### ISSUE THREAD

**Issue by ryan-james-thomas** [turnermm/xcom#8]
The GUI for the xcom plugin no longer responds to user actions.  Clicking on any button does nothing, and the drop down menus are no longer populated.  Looking at the web browser console, when any page on the wiki loads there is a SyntaxError (this only appears when the plugin is installed), and when any button is clicked on the xcom GUI a ReferenceError is thrown.  
![xcom-issue](https://user-images.githubusercontent.com/60238531/115695013-c3361e80-a3a4-11eb-99ab-4dd883fb6a2f.png)
This issue did not exist on the 2020-03-10 update, but does exist on the 2021-04-21 update.

Web browser is Firefox 87.0 (64-bit) for Ubuntu.  PHP is version 7.3.27.

**Comment by turnermm** [comment]
Sorry about that.  I've been working on revisions and  some merge directions accidentally go left in the script.  I noticed it myself this a.m. and fixed it.  You should be ok to re-install.
